# Generated by Django 4.2.30 on 2026-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='identity_document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='proof_of_address',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='transcript_document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
