# Generated by Django 4.2.30 on 2026-05-28 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_alter_scholarshipapplication_identity_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='region',
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='region',
            field=models.CharField(choices=[('Region 1', 'Region 1'), ('Region 2', 'Region 2'), ('Region 3', 'Region 3'), ('Region 4', 'Region 4'), ('Region 5', 'Region 5'), ('Region 6', 'Region 6'), ('Region 7', 'Region 7'), ('Region 8', 'Region 8')], max_length=128),
        ),
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Region 1', 'Region 1'), ('Region 2', 'Region 2'), ('Region 3', 'Region 3'), ('Region 4', 'Region 4'), ('Region 5', 'Region 5'), ('Region 6', 'Region 6'), ('Region 7', 'Region 7'), ('Region 8', 'Region 8')], max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
