# Generated by Django 4.2.30 on 2026-05-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_applicantprofile_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(choices=[('Region 1', 'Region 1'), ('Region 2', 'Region 2'), ('Region 3', 'Region 3'), ('Region 4', 'Region 4'), ('Region 5', 'Region 5'), ('Region 6', 'Region 6'), ('Region 7', 'Region 7'), ('Region 8', 'Region 8')], max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
