# Generated by Django 4.2.30 on 2026-05-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_seed_scholarship_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatorprofile',
            name='region',
        ),
        migrations.AddField(
            model_name='coordinatorprofile',
            name='scholarship_type',
            field=models.CharField(blank=True, choices=[('CHED', 'CHED'), ('TES', 'TES'), ('OTHER', 'Other')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='portal.scholarshipprogram'),
        ),
        migrations.AddField(
            model_name='scholarshipprogram',
            name='scholarship_type',
            field=models.CharField(blank=True, choices=[('CHED', 'CHED'), ('TES', 'TES'), ('OTHER', 'Other')], max_length=64, null=True),
        ),
    ]
