# Generated by Django 4.2.30 on 2026-05-28 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0006_remove_coordinatorprofile_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipprogram',
            name='provider',
        ),
        migrations.AddField(
            model_name='scholarshipprogram',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
