# Generated by Django 4.2.30 on 2026-05-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_scholarshipprogram_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunSQL(
            sql=[
                "INSERT INTO portal_scholarshiptype (id, name, description, created_at) VALUES (1, 'CHED', 'CHED', CURRENT_TIMESTAMP);",
                "INSERT INTO portal_scholarshiptype (id, name, description, created_at) VALUES (2, 'TES', 'TES', CURRENT_TIMESTAMP);",
                "INSERT INTO portal_scholarshiptype (id, name, description, created_at) VALUES (3, 'OTHER', 'Other', CURRENT_TIMESTAMP);",
                "UPDATE portal_coordinatorprofile SET scholarship_type = 1 WHERE scholarship_type = 'CHED';",
                "UPDATE portal_coordinatorprofile SET scholarship_type = 2 WHERE scholarship_type = 'TES';",
                "UPDATE portal_coordinatorprofile SET scholarship_type = 3 WHERE scholarship_type = 'OTHER';",
                "UPDATE portal_scholarshipprogram SET scholarship_type = 1 WHERE scholarship_type = 'CHED';",
                "UPDATE portal_scholarshipprogram SET scholarship_type = 2 WHERE scholarship_type = 'TES';",
                "UPDATE portal_scholarshipprogram SET scholarship_type = 3 WHERE scholarship_type = 'OTHER';",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='scholarship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.scholarshiptype'),
        ),
        migrations.AlterField(
            model_name='scholarshipprogram',
            name='scholarship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.scholarshiptype'),
        ),
    ]
