# Generated by Django 4.2.30 on 2026-05-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_scholarshiptype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarshipapplication',
            old_name='identity_document',
            new_name='birth_certificate',
        ),
        migrations.RenameField(
            model_name='scholarshipapplication',
            old_name='proof_of_address',
            new_name='form_138',
        ),
        migrations.RenameField(
            model_name='scholarshipapplication',
            old_name='transcript_document',
            new_name='proof_of_income',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='title',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='certificate_of_guardianship',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='other_requirements',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.DeleteModel(
            name='EducationBackground',
        ),
    ]
